let letters = "abcdefghijklmnopqrstuvwxyz";
let lettersarray = Array.from(letters);

let letterContainer = document.querySelector(".charcters");

lettersarray.forEach((letters) => {
  let span = document.createElement("span");
  let theLetter = document.createTextNode(letters);
  span.appendChild(theLetter);
  span.className = "Letter-Box";
  letterContainer.appendChild(span);
});

const words = {
  nouns: [
    "abyss",
    "avenue",
    "bagpipes",
    "bandwagon",
    "banjo",
    "bayou",
    "beekeeper",
    "bikini",
    "bookworm",
    "boxcar",
    "boxful",
    "buckaroo",
    "buffalo",
    "buffoon",
    "caliph",
    "cobweb",
    "cockiness",
    "croquet",
    "crypt",
    "curacao",
    "cycle",
    "daiquiri",
    "dirndl",
    "duplex",
    "dwarves",
    "espionage",
    "exodus",
    "fishhook",
    "fjord",
    "flapjack",
    "fluffiness",
    "flyby",
    "foxglove",
    "fuchsia",
    "galaxy",
    "gazebo",
    "giaour",
    "gizmo",
    "glowworm",
    "glyph",
    "gossip",
    "grogginess",
    "haiku",
    "hyphen",
    "icebox",
    "injury",
    "ivory",
    "ivy",
    "jackpot",
    "jaundice",
    "jawbreaker",
    "jelly",
    "jigsaw",
    "jiujitsu",
    "jockey",
    "jukebox",
    "jumbo",
    "kayak",
    "kazoo",
    "keyhole",
    "khaki",
    "kilobyte",
    "kiosk",
    "kitsch",
    "kiwifruit",
    "klutz",
    "knapsack",
    "larynx",
    "lengths",
    "luxury",
    "lymph",
    "marquis",
    "matrix",
    "megahertz",
    "microwave",
    "mystify",
    "naphtha",
    "nightclub",
    "nowadays",
    "numbskull",
    "nymph",
    "onyx",
    "ovary",
    "oxygen",
    "pajama",
    "peekaboo",
    "phlegm",
    "pixel",
    "polka",
    "puppy",
    "quartz",
    "queue",
    "quorum",
    "rhubarb",
    "rhythm",
    "rickshaw",
    "schnapps",
    "scratch",
    "shiv",
    "sphinx",
    "staff",
    "strength",
    "strengths",
    "stretch",
    "stronghold",
    "subway",
    "swivel",
    "syndrome",
    "thumbscrew",
    "topaz",
    "transcript",
    "triphthong",
    "twelfth",
    "twelfths",
    "unknown",
    "uptown",
    "vixen",
    "vodka",
    "voodoo",
    "vortex",
    "voyeurism",
    "walkway",
    "waltz",
    "wave",
    "wellspring",
    "whiskey",
    "whomever",
    "wimpy",
    "witchcraft",
    "wizard",
    "wristwatch",
    "wyvern",
    "xylophone",
    "yachtsman",
    "youthful",
    "yummy",
    "zodiac",
    "zombie",
    "mirror",
    "bicycle",
    "furniture",
    "volcano",
    "mountain",
    "carpet",
    "universe",
    "treasure",
    "revolution",
    "scientist",
    "airplane",
    "trampoline",
    "television",
    "radio",
    "computer",
    "shoes",
    "television",
    "cabin",
    "clock",
    "dream",
    "light",
    "sun",
    "star",
    "blackhole",
    "ocean",
    "crater",
    "country",
    "city",
    "island",
    "forest",
    "desert",
    "hotel",
    "restaurant",
    "knife",
    "plate",
    "book",
    "notebook",
    "classroom",
    "lecture",
    "professor",
    "table",
    "window",
    "door",
    "train",
    "plane",
    "bus",
    "truck",
    "trolley",
    "map",
    "bus stop",
    "subway station",
    "laptop",
    "phone",
    "television",
  ],

  verbs: [
    "affix",
    "boggle",
    "disavow",
    "embezzle",
    "equip",
    "faking",
    "flopping",
    "galvanize",
    "jaywalk",
    "jogging",
    "joking",
    "oxidize",
    "unzip",
    "vaporize",
    "calculate",
    "analyze",
    "visualize",
    "investigate",
    "travel",
    "discover",
    "organize",
    "create",
    "manage",
    "enlighten",
    "dance",
    "sing",
    "run",
    "jump",
    "climb",
    "speak",
    "write",
    "read",
    "drive",
    "swim",
    "walk",
    "play",
    "build",
    "destroy",
    "comprehend",
    "understand",
    "grow",
    "decrease",
    "inflate",
    "deflate",
    "push",
    "pull",
    "take",
    "give",
    "receive",
    "accept",
    "reject",
    "pass",
    "fail",
    "ask",
    "answer",
    "remember",
    "forget",
    "help",
    "assist",
    "lead",
    "follow",
    "interview",
    "teach",
    "learn",
    "understand",
    "run",
    "skip",
    "pause",
    "stop",
    "restart",
    "drive",
    "arrive",
    "depart",
    "instruct",
    "call",
    "start",
    "stop",
    "close",
    "open",
    "launch",
    "finish",
    "prepare",
    "deliver",
    "distribute",
    "fetch",
    "fix",
    "construct",
    "deconstruct",
    "describe",
    "explain",
    "analyze",
    "research",
    "edit",
    "show",
    "present",
    "discuss",
    "complete",
    "rebuild",
    "copy",
    "paste",
    "cut",
    "select",
    "mark",
    "check",
    "monitor",
    "scan",
    "recycle",
    "split",
    "combine",
    "join",
    "connect",
    "disconnect",
    "fix",
    "modify",
    "assemble",
  ],

  adjectives: [
    "abruptly",
    "absurd",
    "askew",
    "awkward",
    "blitz",
    "blizzard",
    "dizzying",
    "funny",
    "gabby",
    "gnarly",
    "haphazard",
    "iatrogenic",
    "jazziest",
    "jazzy",
    "jovial",
    "joyful",
    "juicy",
    "lucky",
    "puzzling",
    "quixotic",
    "snazzy",
    "spritz",
    "squawk",
    "stymied",
    "thriftless",
    "unworthy",
    "wavy",
    "waxy",
    "wheezy",
    "whizzing",
    "woozy",
    "yippee",
    "yoked",
    "delightful",
    "astonishing",
    "brilliant",
    "incredible",
    "wonderful",
    "beautiful",
    "horrible",
    "devastating",
    "intense",
    "sharp",
    "unpredictable",
    "fast",
    "slow",
    "sweet",
    "sour",
    "bitter",
    "intelligent",
    "cunning",
    "wise",
    "kind",
    "angry",
    "friendly",
    "shy",
    "timid",
    "honest",
    "brave",
    "strong",
    "weak",
    "stubborn",
    "flexible",
    "calm",
    "gentle",
    "fierce",
    "determined",
    "delicate",
    "fearful",
    "optimistic",
    "pessimistic",
    "courageous",
    "excited",
    "creative",
    "exciting",
    "strange",
    "peculiar",
    "odd",
    "weird",
    "fantastic",
    "inspirational",
    "sparkling",
    "smooth",
    "rough",
    "charming",
    "wonderful",
    "awful",
    "energetic",
    "lazy",
    "confident",
    "anxious",
    "alert",
    "weak",
    "strong",
    "adventurous",
    "ambitious",
  ],

  programmingLanguages: [
    "javascript",
    "python",
    "java",
    "csharp",
    "ruby",
    "swift",
    "go",
    "rust",
    "php",
    "typescript",
    "kotlin",
    "scala",
    "perl",
    "lua",
    "haskell",
    "elixir",
    "clojure",
    "dart",
    "r",
    "matlab",
    "sql",
    "html",
    "css",
    "xml",
    "json",
    "bash",
    "typescript",
    "ruby",
    "powershell",
    "fortran",
    "c",
    "cpp",
    "vhdl",
    "prolog",
    "racket",
    "scratch",
    "actionscript",
    "nodejs",
    "ajax",
    "sass",
    "scss",
    "fsharp",
    "swift",
    "go",
    "cobol",
    "delphi",
    "vhdl",
    "mathematica",
    "objective c",
    "scheme",
    "labview",
    "smalltalk",
    "ocaml",
    "visual basic",
    "elixir",
    "delphi",
    "groovy",
    "verilog",
    "markdown",
    "julia",
  ],

  celebrities: [
    "einstein",
    "newton",
    "galileo",
    "tesla",
    "hawking",
    "curie",
    "jobs",
    "gates",
    "bezos",
    "musk",
    "oprah",
    "madonna",
    "shakespeare",
    "lincoln",
    "darwin",
    "turing",
    "churchill",
    "marilyn monroe",
    "walt disney",
    "bob dylan",
    "john lennon",
    "frida kahlo",
    "albert einstein",
    "martin luther king",
    "federer",
    "cristiano ronaldo",
    "michael jordan",
    "elvis presley",
    "michael jackson",
    "georgewashington",
    "winston churchill",
    "ronaldo",
    "messi",
    "roger federer",
    "neil armstrong",
    "socrates",
    "plato",
    "aristotle",
    "galileo",
    "charles darwin",
    "vinci",
    "gandhi",
    "benjamin franklin",
    "vladimir lenin",
  ],

  historicalEvents: [
    "world war 1",
    "world war 2",
    "french revolution",
    "fall of rome",
    "moon landing",
    "cold war",
    "industrial revolution",
    "arab spring",
    "battle of waterloo",
    "hiroshima bombing",
    "battle of thermopylae",
    "kingdom of hejaz",
    "tiananmen square massacre",
    "sinking of titanic",
    "civil rights movement",
    "moon landing",
    "fall of wall",
    "soviet invasion",
    "global warming awareness",
    "evolution theory accepted",
    "renaissance",
    "discovery of america",
    "founding of the united nations",
    "rise of nazism",
    "discovery of america",
    "ww1 end",
    "ww2 end",
    "american civil war",
    "hurricane katrina",
    "george washington inauguration",
    "cold war",
    "french revolution",
  ],

  historicalFigures: [
    "alexander",
    "caesar",
    "cleopatra",
    "saladin",
    "genghis",
    "napoleon",
    "lincoln",
    "hitler",
    "churchill",
    "mandela",
    "socrates",
    "plato",
    "aristotle",
    "galileo",
    "charles darwin",
    "vinci",
    "gandhi",
    "benjamin franklin",
    "vladimir lenin",
    "marx",
    "locke",
    "heisenberg",
    "shakespeare",
    "walt disney",
    "einstein",
    "newton",
    "confucius",
    "socrates",
    "plato",
    "aristotle",
    "galileo",
  ],

  planets: [
    "mercury",
    "venus",
    "earth",
    "mars",
    "jupiter",
    "saturn",
    "uranus",
    "neptune",
    "pluto",
    "eris",
    "ceres",
    "haumea",
    "makemake",
    "planet x",
    "charon",
    "moon",
    "phobos",
    "deimos",
    "titan",
    "io",
    "europa",
    "ganymede",
    "callisto",
    "enceladus",
  ],

  arabCelebrities: [
    "umm kulthum",
    "fairuz",
    "nizar qabbani",
    "adel imam",
    "ahmed helmy",
    "nancy ajram",
    "majida el roumi",
    "amr diab",
    "ragheb alama",
    "assala",
    "mohamed monsoor",
    "tamer hosny",
    "elissa",
    "yara",
    "assala nabil",
    "fayrouz",
    "tamer hosny",
    "mohamed monsour",
  ],

  arabicFoods: [
    "hummus",
    "falafel",
    "shawarma",
    "kabsa",
    "mansaf",
    "mloukhieh",
    "maqluba",
    "koshari",
    "tabbouleh",
    "fattoush",
    "makbous",
    "molokhia",
    "pita bread",
    "sfiha",
    "fattah",
    "meatballs",
    "baklava",
    "tabbouleh",
    "meze",
    "mutabbal",
  ],

  europeanFoods: [
    "pizza",
    "pasta",
    "paella",
    "croissant",
    "ratatouille",
    "goulash",
    "schnitzel",
    "bratwurst",
    "pierogi",
    "bangers and mash",
    "sauerbraten",
    "spaghetti",
    "bruschetta",
    "strudel",
    "baba ghannouj",
    "caviar",
    "moussaka",
    "gnocchi",
    "frittata",
    "quiche",
  ],
  famousLandmarks: [
    "Eiffel Tower",
    "Great Wall of China",
    "Taj Mahal",
    "Pyramids of Giza",
    "Colosseum",
    "Machu Picchu",
    "Christ the Redeemer",
    "Sydney Opera House",
    "Big Ben",
    "Statue of Liberty",
    "Acropolis of Athens",
    "Stonehenge",
    "Mount Rushmore",
    "Louvre Museum",
    "Mount Fuji",
    "Sagrada Familia",
    "Chichen Itza",
    "Palace of Versailles",
    "Alhambra",
    "Neuschwanstein Castle",
    "Petra",
    "Burj Khalifa",
    "Mount Kilimanjaro",
    "Angkor Wat",
    "The Leaning Tower of Pisa",
    "Brandenburg Gate",
    "Buckingham Palace",
    "Machu Picchu",
    "Palace of the Parliament",
    "Fallingwater",
    "Blue Mosque",
    "Alcatraz",
    "Golden Gate Bridge",
    "Notre-Dame Cathedral",
    "Buckingham Palace",
    "Sistine Chapel",
    "Forbidden City",
    "Arlington Cemetery",
    "Mount Etna",
    "Mount Vesuvius",
    "Uluru",
    "Table Mountain",
    "Great Barrier Reef",
    "St. Peter's Basilica",
    "Royal Palace of Madrid",
    "Lagos de Covadonga",
    "Kremlin",
    "Statue of Liberty",
    "Golden Temple",
    "Stone Mountain",
    "Acropolis Museum",
    "Fisherman's Wharf",
    "Kilimanjaro National Park",
    "Babel Tower",
    "Machu Picchu",
    "Mount Ararat",
    "Lake Baikal",
    "Brandenburg Gate",
    "Reichstag Building",
    "Santorini",
    "Chichen Itza",
    "Tikal",
    "Cairo Tower",
    "Moai Statues",
    "Karnak Temple",
    "Hagia Sophia",
  ],

  mythicalCreatures: [
    "Dragon",
    "Phoenix",
    "Unicorn",
    "Griffin",
    "Mermaid",
    "Centaur",
    "Hydra",
    "Yeti",
    "Loch Ness Monster",
    "Vampire",
    "Werewolf",
    "Zombie",
    "Gorgon",
    "Basilisk",
    "Minotaur",
    "Sphinx",
    "Kraken",
    "Chimera",
    "Witch",
    "Sorcerer",
    "Genie",
    "Jinn",
    "Troll",
    "Goblin",
    "Valkyrie",
    "Banshee",
    "Vampire Bat",
    "Chupacabra",
    "Cheshire Cat",
    "Wendigo",
    "Manticore",
    "Mummy",
    "Cyclops",
    "Baku",
    "Kitsune",
    "Kappa",
    "Yokai",
    "Tengu",
    "Ogre",
    "Werecat",
    "Mokele-Mbembe",
    "Selkie",
    "Kelpie",
    "Fey",
    "Bigfoot",
    "Thunderbird",
    "Sasquatch",
    "Skinwalker",
    "Jorogumo",
    "Tikbalang",
    "Fawn",
    "Faun",
    "Hippogriff",
    "Baba Yaga",
    "Furies",
    "Nymph",
    "Satyr",
    "Harpies",
    "Selkies",
    "Basilisk",
    "Poltergeist",
    "Leprechaun",
    "Fairy",
    "Chimera",
    "Dragon Turtle",
    "Jorogumo",
    "Grendel",
    "Wraith",
    "Sirens",
    "Kitsune",
    "Argonaut",
    "Bugbear",
    "Aswang",
    "Hollow Men",
    "Gorgon",
    "Manticore",
    "Ithaca",
    "Sasquatch",
    "Yowie",
    "Ogopogo",
    "Mokele Mbembe",
    "Thylacine",
    "Mokele-mbembe",
    "Trolls",
    "Minotaur",
    "Wendigo",
    "Elves",
  ],

  famousArtists: [
    "Picasso",
    "Van Gogh",
    "Da Vinci",
    "Monet",
    "Dali",
    "Michelangelo",
    "Rembrandt",
    "Vermeer",
    "Warhol",
    "Matisse",
    "Renoir",
    "Goya",
    "Cezanne",
    "Munch",
    "Klimt",
    "Kandinsky",
    "Pollock",
    "Kahlo",
    "Degas",
    "Botticelli",
    "Hokusai",
    "Manet",
    "Caravaggio",
    "Turner",
    "Hopper",
    "Rothko",
    "Lichtenstein",
    "Rauschenberg",
    "Basquiat",
    "Klee",
    "Modigliani",
    "Cassatt",
    "Hockney",
    "Sargent",
    "Chagall",
    "Haring",
    "Warhol",
    "Pollock",
    "Friedrich",
    "Vasarely",
    "Koons",
    "Judd",
    "Kooning",
    "Wright",
    "Léger",
    "Giotto",
    "Van Gogh",
    "Breton",
    "Caravaggio",
    "Soutine",
    "Toulouse-Lautrec",
    "Bacon",
    "Nash",
    "Dalí",
    "Picasso",
    "Klee",
    "Botticelli",
    "Guggenheim",
    "Giacometti",
    "Wood",
    "Hepworth",
    "Eliasson",
    "Burri",
    "Magritte",
    "Abakanowicz",
    "Braque",
    "Bacon",
    "Bürgi",
    "Canova",
    "Degas",
    "Cadell",
    "Balla",
    "Benin",
    "Archipenko",
    "Tanguy",
    "Chareau",
    "Reinhardt",
    "Vasarely",
    "Matta",
    "Freud",
  ],

  popularMovies: [
    "Titanic",
    "Avatar",
    "The Godfather",
    "Star Wars",
    "Jurassic Park",
    "The Dark Knight",
    "Pulp Fiction",
    "Forrest Gump",
    "Inception",
    "The Shawshank Redemption",
    "The Matrix",
    "The Lord of the Rings",
    "Avengers: Endgame",
    "The Lion King",
    "Gladiator",
    "Frozen",
    "The Wizard of Oz",
    "Fight Club",
    "The Silence of the Lambs",
    "Casablanca",
    "Gone with the Wind",
    "Schindler's List",
    "The Terminator",
    "Back to the Future",
    "The Social Network",
    "Interstellar",
    "The Hunger Games",
    "The Princess Bride",
    "E.T.",
    "The Exorcist",
    "The Godfather: Part II",
    "Inglourious Basterds",
    "Jaws",
    "The Usual Suspects",
    "Blade Runner",
    "The Big Lebowski",
    "Citizen Kane",
    "12 Angry Men",
    "The Seventh Seal",
    "A Clockwork Orange",
    "The Departed",
    "The Shining",
    "The Good, the Bad, and the Ugly",
    "The Truman Show",
    "Saving Private Ryan",
    "The Green Mile",
    "Braveheart",
    "The Pursuit of Happyness",
    "The Incredibles",
    "Spider-Man",
    "Avatar",
    "Guardians of the Galaxy",
    "The Avengers",
    "Mad Max: Fury Road",
    "Deadpool",
    "Iron Man",
    "The Matrix Reloaded",
    "Django Unchained",
    "Gladiator",
    "Harry Potter",
    "The Lord of the Rings",
    "Skyfall",
    "Casino Royale",
    "Die Hard",
    "The Pianist",
    "The Help",
    "The Revenant",
    "Whiplash",
    "The Wolf of Wall Street",
    "The Big Short",
    "La La Land",
    "Arrival",
    "The Martian",
  ],
};

let allkeys = Object.keys(words);
let randomPronum = Math.floor(Math.random() * allkeys.length);
let randomproname = allkeys[randomPronum];
let randomprovalue = words[randomproname];
let randomvaluenum = Math.floor(Math.random() * randomprovalue.length);
let randomvaluename = randomprovalue[randomvaluenum];
document.querySelector(".game-info .word-from span").innerHTML = randomproname;
let letterGuess = document.querySelector(".letter-guess");
let randomArray = Array.from(randomvaluename);
randomArray.forEach((letters) => {
  let span = document.createElement("span");
  span.className = "letter";
  if (letters === " ") {
    span.className = "space";
  }

  letterGuess.appendChild(span);
});
let wrongAttemps = 0;
let lettersGuess = document.querySelectorAll(".letter-guess .letter");
let randamvalue = Array.from(randomvaluename.toLowerCase());
document.addEventListener("click", (e) => {
  let thestatus = false;

  if (e.target.className === "Letter-Box") {
    e.target.classList.add("clicked");
    let letterChosen = e.target.innerHTML.toLowerCase();
    randamvalue.forEach((wordletter, index) => {
      if (letterChosen == wordletter) {
        thestatus = true;
        lettersGuess.forEach((span, letterindex) => {
          if (index === letterindex) {
            span.innerHTML = letterChosen;
          }
        });
      }
    });
    if (thestatus !== true) {
      wrongAttemps++;
      let theDraw = document.querySelector(".the-draw");
      theDraw.classList.add(`wrong-${wrongAttemps}`);
      if (wrongAttemps === 7) {
        endGame();
        letterContainer.classList.add("finished");
      }
    }
  }
});

function endGame() {
  // Create Popup Div
  let div = document.createElement("div");

  // Create Text
  let divText = document.createTextNode(
    `Game Over, The Word Is ${randomvaluename}`
  );

  // Append Text To Div
  div.appendChild(divText);

  // Add Class On Div
  div.className = "popup";

  // Append To The Body
  document.body.appendChild(div);
}
